---
title: "Bridges homework"
author: "Faith Kulzer"
date: "2/4/2021"
output: github_document
---

```{r warning = FALSE, message = FALSE}
library('readr')
library('data.table')
library('tidyverse')
bridges <- fread("https://www.fhwa.dot.gov/bridge/nbi/2019/delimited/WI19.txt")

##link to my github: https://github.com/fkulzer/Bridges-homework


##filter out useful columns, rename
bridges_filtered <- bridges %>%
  select(STRUCTURE_NUMBER_008, COUNTY_CODE_003, DECK_COND_058, SUPERSTRUCTURE_COND_059, SUBSTRUCTURE_COND_060, YEAR_BUILT_027, ADT_029, LAT_016, LONG_017) %>%
  rename(bridge_id = STRUCTURE_NUMBER_008, fip_code = COUNTY_CODE_003, deck_cond = DECK_COND_058, super_cond = SUPERSTRUCTURE_COND_059, sub_cond = SUBSTRUCTURE_COND_060, year = YEAR_BUILT_027, adt = ADT_029, latitude = LAT_016, longitude = LONG_017)

head(bridges_filtered)
```

```{r warning = FALSE}
ggplot(bridges_filtered, aes(x=latitude, y=adt)) +
  geom_point(size=0.4) +
  xlab("Latitude") +
  ylab("Average Daily Travel") 
```

This graph shows the average daily travel for each bridge by the latitude coordinate of the bridge. The visible 'groups' of the longitude may be due to a precision that is too low. 
